# Generated by Django 2.0.5 on 2018-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DoorPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('is_hard', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('apply_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('due_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
