# Generated by Django 2.0.5 on 2018-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorhistory',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
