# Generated by Django 2.0.5 on 2018-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_auto_20180514_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorhistory',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
